### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by PedroGao** [all4you/redant#2]
我看到了redant里面用到了threadlocal才存放一些重要的信息。对于netty这种异步的框架而言，同一个线程是会处理多个不同的请求的，这样做，是否正确？
我对此有些疑惑，可能是我知识有限，烦请解答一下，谢谢了。

**Comment by all4you** [comment]
可以了解下 Netty 的 EventLoop 的执行过程，以及 Netty 的串行化设计。
另外 ThreadLocal 本身就是一种解决线程安全的方案，跟 Netty 没有关系。
同一个线程中处理多个不同的请求，如果每个请求的 Handler 都能保证是线程安全的，那就是安全的，和是否使用 ThreadLocal 没有太大的关系。

**Comment by pedrogao** [comment]
打扰到了，我还是得追问一下。
Netty既然可以在单个线程里面处理多个不同的Handler，每个Handler都有其自己的session信息，这些放在ThreadLocal里面，公用一个线程的多个Handler的session信息可能就会造成污染。
例如：Handler1在ThreadLocal里面存放了session1，而同一线程的Handler2就有可能在同一时间通过ThreadLocal取到session1，那么就造成污染。
请问，您上面提到的Handler线程安全是如何保证ThreadLocal在这里安全的？谢谢了
